### ISSUE TITLE
mark as deprecated?

### ISSUE THREAD

**Issue by jgravois** [Esri/geojson-utils#16]
i think it would be helpful for folks if the bold note at the top about Terraformer were even more exaggerated and included language like 'Deprecated'.  we might even consider pointing people to [arcgis-to-geojson-utils](https://github.com/Esri/arcgis-to-geojson-utils) instead of Terraformer.

what do you think @jcardonadcdev? @ajturner? @patrickarlt?

Esri/vector-tile-layer#6

**Comment by jcardonadcdev** [comment]
Sounds good to me. If everybody agrees, I can make the changes to the README

**Comment by jgravois** [comment]
im happy to PR them too.  (i like to try to be more than a complainer).

**Comment by jcardonadcdev** [comment]
OK. Feel free to make a PR and reference this issue. Thanks!

**Comment by ajturner** [comment]
Is Terraformer deprecated? It provides a lot more than just GeoJSON conversion and used by the US Census and others.

**Comment by jgravois** [comment]
> Is Terraformer deprecated?

no, no.  im suggesting that we mark *geojson-utils* as deprecated and point people at both Terraformer and arcgis-to-geojson-utils instead.
