### ISSUE TITLE
Order of points in GeoJSON Polygon/MultiPolygon rings

### ISSUE THREAD

**Issue by rxsands** [Esri/geojson-utils#7]
There seems to be missing functionality in the gcCoordinatesToEsriCoordinates to process GeoJSON Polygon and MultiPolygon rings.  Per the GeoJSON spec at http://www.geojson.org/geojson-spec.html#polygon, the a Polygon consists of an array of rings, the first being the exterior ring, and the rest (if any) being the inner ring(s).  The problem is that the GeoJSON spec doesn't mandate a clockwise/counter-clockwise order for either type of ring.  The MultiPolygon wraps multiple polygons of this format, so the same processing of inner vs. outer rings needs to happen there.  It seems like each GeoJSON ring must be tested to determine if clockwise or counter-clockwise and the points would be reversed as necessary for ArcGIS, which denotes inner rings by ordering in a counter-clockwise fashion.

This thread describes the problem in point ordering in GeoJSON polygons (and LineString!): http://lists.geojson.org/pipermail/geojson-geojson.org/2007-October/000273.html.  The polygon can be ambiguous without a known order for the points.

**Comment by sjlynch** [comment]
Hey did you ever find a good solution for this? I'm parsing geojson and throwing vertices at Threejs and I am getting a lot of triangulation warnings, I think because the order of vertices is not always consistent.

**Comment by jcardonadcdev** [comment]
@sjlynch - There was a bug in the conversion of geojson 'MultiPolygon' types. That is fixed. As far as I can tell, rings are getting oriented correctly. Also, have you looked at https://github.com/Esri/Terraformer? It has geojson conversion functions and has more functionality than what is in this code.

**Comment by sjlynch** [comment]
Holy cow! No I hadn't seen Terraformer, looks perfect for my use-case, thank you!
